name: Container Security Scan

on:
  push:
    branches: [master, develop]
    paths:
      - 'Dockerfile'
      - '.github/workflows/container-security.yml'
  pull_request:
    branches: [master]
    paths:
      - 'Dockerfile'
  schedule:
    - cron: '0 2 * * 1' # Weekly on Monday at 2 AM

jobs:
  container-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Build Docker image
        run: |
          docker build -t local/security-scan:latest .

      - name: Run container structure tests
        run: |
          # Install container-structure-test
          curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64
          sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test

          # Create test config
          cat > container-tests.yaml << 'EOF'
          schemaVersion: 2.0.0
          fileExistenceTests:
            - name: 'app directory exists'
              path: '/app'
              shouldExist: true
              isDirectory: true
            - name: 'node_modules should not exist in final image'
              path: '/app/node_modules'
              shouldExist: false
          commandTests:
            - name: 'check if app starts'
              command: 'node'
              args: ['--version']
              expectedOutput: ['v23.*']
          metadataTest:
            exposedPorts: ['3000']
            user: 'nextjs'
            workdir: '/app'
          EOF

          # Run tests
          container-structure-test test --image local/security-scan:latest --config container-tests.yaml

      - name: Check for vulnerabilities with Grype
        run: |
          # Install Grype
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

          # Scan the image
          grype local/security-scan:latest --fail-on medium --output json --file grype-report.json || echo "Vulnerabilities found"

          # Show summary
          grype local/security-scan:latest --output table

      - name: Upload security scan results
        uses: actions/upload-artifact@84480863f228bb9747b473957fcc9e309aa96097 # v4.4.2
        if: always()
        with:
          name: security-scan-results
          path: |
            grype-report.json
          retention-days: 30